# Generated by Django 5.0.1 on 2024-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(default='blank.jpg', upload_to='profile_img'),
        ),
    ]
